spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/library
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
  #Обработка ошибки NoHandlerFoundException в @ControllerAdvice при переходе на неизвестный url
  web:
    resources.add-mappings: false
  #Туннелирование запроса DELETE через POST
  mvc:
    hiddenmethod:
      filter:
        enabled: true